import {CharacterController} from "./controller/CharacterController";

export const Routes = [
  {
    method: "get",
    route: "/characters/:characterId",
    controller: CharacterController,
    action: "getCharacterById"
  }, {
    method: "get",
    route: "/characters/user/:username",
    controller: CharacterController,
    action: "getCharactersByUsername"
  }, {
    method: "post",
    route: "/characters",
    controller: CharacterController,
    action: "createCharacter"
  }, {
    method: "put",
    route: "/characters/:characterId",
    controller: CharacterController,
    action: "updateCharacterById"
  }, {
    method: "put",
    route: "/characters/:characterId/death_saves",
    controller: CharacterController,
    action: "updateCharacterDeathSaves"
  }, {
    method: "put",
    route: "/characters/:characterId/known_spells",
    controller: CharacterController,
    action: "updateKnownSpells"
  }, {
    method: "put",
    route: "/characters/:characterId/known_spells/:level",
    controller: CharacterController,
    action: "updateKnownSpellsAtLevel"
  }, {
    method: "put",
    route: "/characters/:characterId/ability_scores",
    controller: CharacterController,
    action: "updateAbilityScores"
  }, {
    method: "post",
    route: "/characters/:characterId/features_and_traits",
    controller: CharacterController,
    action: "createFeatureAndTrait"
  }, {
    method: "post",
    route: "/characters/:characterId/features_and_traits/bulk",
    controller: CharacterController,
    action: "createFeaturesAndTraits"
  }, {
    method: "put",
    route: "/characters/:characterId/features_and_traits/",
    controller: CharacterController,
    action: "updateFeatureAndTrait"
  }, {
    method: "put",
    route: "/characters/:characterId/features_and_traits/bulk",
    controller: CharacterController,
    action: "updateFeaturesAndTraits"
  }, {
    method: "delete",
    route: "/characters/:characterId/features_and_traits/:fatId",
    controller: CharacterController,
    action: "deleteFeatureAndTrait"
  }, {
    method: "put",
    route: "/characters/:characterId/spell_slots/",
    controller: CharacterController,
    action: "updateSpellSlots"
  }, {
    method: "put",
    route: "/characters/:characterId/spell_slots/:level",
    controller: CharacterController,
    action: "updateSpellSlotsAtLevel"
  }, {
    method: "put",
    route: "/characters/:characterId/treasure/money",
    controller: CharacterController,
    action: "updateTreasureMoney"
  }, {
    method: "put",
    route: "/characters/:characterId/treasure/items/:id",
    controller: CharacterController,
    action: "updateTreasureItem"
  }, {
    method: "post",
    route: "/characters/:characterId/treasure/items",
    controller: CharacterController,
    action: "createTreasureItem"
  }, {
    method: "delete",
    route: "/characters/:characterId/treasure/items/:id",
    controller: CharacterController,
    action: "deleteTreasureItem"
  }, {
    method: "put",
    route: "/characters/:characterId/settings",
    controller: CharacterController,
    action: "updateCharacterSettings"
  }, {
    method: "post",
    route: "/characters/:characterId/hit_dice",
    controller: CharacterController,
    action: "createHitDice"
  }, {
    method: "delete",
    route: "/characters/:characterId/hit_dice/:id",
    controller: CharacterController,
    action: "deleteHitDice"
  }, {
    method: "put",
    route: "/characters/:characterId/hit_dice/:id",
    controller: CharacterController,
    action: "updateHitDice"
  }
];


